DROP TABLE IF EXISTS "Friendship" CASCADE;
DROP TABLE IF EXISTS "DMParticipant" CASCADE;
DROP TABLE IF EXISTS "DirectMessage" CASCADE;
DROP TABLE IF EXISTS "DMConversation" CASCADE;
DROP TABLE IF EXISTS "Server" CASCADE;
